In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/ieee-fraud-detection/sample_submission.csv
/kaggle/input/competitions/ieee-fraud-detection/test_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/test_transaction.csv
/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv

In [2]:
!pip install dagshub
!pip install mlflow

Requirement already satisfied: dagshub in /usr/local/lib/python3.12/dist-packages (0.7.0)
Requirement already satisfied: PyYAML>=5 in /usr/local/lib/python3.12/dist-packages (from dagshub) (6.0.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: click>=8.0.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (8.3.1)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: GitPython>=3.1.29 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.1.46)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.12/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.3.3)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.42.70)
Requirement already satisfied: semver in /usr/local/lib/python3.12/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.2.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (2.12.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from GitPython>=3.1.29->dagshub) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.19.2)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from treelib>=1.6.4->dagshub) (1.17.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.70 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.42.70)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.16.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: graphql-core<3.3,>=3.2 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (3.2.8)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.22.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests<3,>=2.26 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (2.32.4)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->dagshub) (2025.3)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.70->boto3->dagshub) (2.5.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.12/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->dagshub) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.26->gql[requests]->dagshub) (3.4.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.4.1)
Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.11.1)
Requirement already satisfied: mlflow-skinny==3.11.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.11.1)
Requirement already satisfied: mlflow-tracing==3.11.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.11.1)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /usr/local/lib/python3.12/dist-packages (from mlflow) (25.3.0)
Requirement already satisfied: huey<3,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.47)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.106.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.133.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (5.29.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.41.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.22.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.1.4)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (5.0.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.40.0->fastapi<1->mlflow-skinny==3.11.1->mlflow) (4.12.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.6.2)

In [3]:
import dagshub
dagshub.init(repo_owner='icosahedron31', repo_name='IEEE-CIS-Fraud-Detection', mlflow=True)

Accessing as icosahedron31

Initialized MLflow to track repo "icosahedron31/IEEE-CIS-Fraud-Detection"

Repository icosahedron31/IEEE-CIS-Fraud-Detection initialized!

# Reading Data

In [4]:
df_identity = pd.read_csv("/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv")

In [5]:
df_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionID  144233 non-null  int64
 1   id_01          144233 non-null  float64
 2   id_02          140872 non-null  float64
 3   id_03          66324 non-null   float64
 4   id_04          66324 non-null   float64
 5   id_05          136865 non-null  float64
 6   id_06          136865 non-null  float64
 7   id_07          5155 non-null    float64
 8   id_08          5155 non-null    float64
 9   id_09          74926 non-null   float64
 10  id_10          74926 non-null   float64
 11  id_11          140978 non-null  float64
 12  id_12          144233 non-null  object
 13  id_13          127320 non-null  float64
 14  id_14          80044 non-null   float64
 15  id_15          140985 non-null  object
 16  id_16          129340 non-null  object
 17  id_17          139369 non-null  float64
 18  id_18          45113 non-null   float64
 19  id_19          139318 non-null  float64
 20  id_20          139261 non-null  float64
 21  id_21          5159 non-null    float64
 22  id_22          5169 non-null    float64
 23  id_23          5169 non-null    object
 24  id_24          4747 non-null    float64
 25  id_25          5132 non-null    float64
 26  id_26          5163 non-null    float64
 27  id_27          5169 non-null    object
 28  id_28          140978 non-null  object
 29  id_29          140978 non-null  object
 30  id_30          77565 non-null   object
 31  id_31          140282 non-null  object
 32  id_32          77586 non-null   float64
 33  id_33          73289 non-null   object
 34  id_34          77805 non-null   object
 35  id_35          140985 non-null  object
 36  id_36          140985 non-null  object
 37  id_37          140985 non-null  object
 38  id_38          140985 non-null  object
 39  DeviceType     140810 non-null  object
 40  DeviceInfo     118666 non-null  object
dtypes: float64(23), int64(1), object(17)
memory usage: 45.1+ MB

In [6]:
df_transaction = pd.read_csv("/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv")

In [7]:
df_transaction.info(), df_transaction.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), object(14)
memory usage: 1.7+ GB

(None,
        TransactionID        isFraud  TransactionDT  TransactionAmt  \
 count   5.905400e+05  590540.000000   5.905400e+05   590540.000000
 mean    3.282270e+06       0.034990   7.372311e+06      135.027176
 std     1.704744e+05       0.183755   4.617224e+06      239.162522
 min     2.987000e+06       0.000000   8.640000e+04        0.251000
 25%     3.134635e+06       0.000000   3.027058e+06       43.321000
 50%     3.282270e+06       0.000000   7.306528e+06       68.769000
 75%     3.429904e+06       0.000000   1.124662e+07      125.000000
 max     3.577539e+06       1.000000   1.581113e+07    31937.391000

                card1          card2          card3          card5  \
 count  590540.000000  581607.000000  588975.000000  586281.000000
 mean     9898.734658     362.555488     153.194925     199.278897
 std      4901.170153     157.793246      11.336444      41.244453
 min      1000.000000     100.000000     100.000000     100.000000
 25%      6019.000000     214.000000     150.000000     166.000000
 50%      9678.000000     361.000000     150.000000     226.000000
 75%     14184.000000     512.000000     150.000000     226.000000
 max     18396.000000     600.000000     231.000000     237.000000

                addr1          addr2  ...          V330           V331  \
 count  524834.000000  524834.000000  ...  82351.000000   82351.000000
 mean      290.733794      86.800630  ...      0.775874     721.741883
 std       101.741072       2.690623  ...      4.727971    6217.223583
 min       100.000000      10.000000  ...      0.000000       0.000000
 25%       204.000000      87.000000  ...      0.000000       0.000000
 50%       299.000000      87.000000  ...      0.000000       0.000000
 75%       330.000000      87.000000  ...      0.000000       0.000000
 max       540.000000     102.000000  ...     55.000000  160000.000000

                 V332           V333          V334         V335          V336  \
 count   82351.000000   82351.000000  82351.000000  82351.00000  82351.000000
 mean     1375.783644    1014.622782      9.807015     59.16455     28.530903
 std     11169.275702    7955.735482    243.861391    387.62948    274.576920
 min         0.000000       0.000000      0.000000      0.00000      0.000000
 25%         0.000000       0.000000      0.000000      0.00000      0.000000
 50%         0.000000       0.000000      0.000000      0.00000      0.000000
 75%        25.000000       0.000000      0.000000      0.00000      0.000000
 max    160000.000000  160000.000000  55125.000000  55125.00000  55125.000000

                 V337           V338           V339
 count   82351.000000   82351.000000   82351.000000
 mean       55.352422     151.160542     100.700882
 std       668.486833    1095.034387     814.946722
 min         0.000000       0.000000       0.000000
 25%         0.000000       0.000000       0.000000
 50%         0.000000       0.000000       0.000000
 75%         0.000000       0.000000       0.000000
 max    104060.000000  104060.000000  104060.000000

 [8 rows x 380 columns])

In [8]:
df_transaction.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_train = df_transaction.merge(df_identity, on='TransactionID', how='left')
df_train.columns

Index(['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5',
       ...
       'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38',
       'DeviceType', 'DeviceInfo'],
      dtype='object', length=434)

In [10]:
df_train.head(20)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.500,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.000,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.000,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.000,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.000,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
5,2987005,0,86510,49.000,W,5937,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2987006,0,86522,159.000,W,12308,360.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2987007,0,86529,422.500,W,12695,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2987008,0,86535,15.000,H,2803,100.0,150.0,visa,226.0,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
9,2987009,0,86536,117.000,W,17399,111.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2987010,0,86549,75.887,C,16496,352.0,117.0,mastercard,134.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
11,2987011,0,86555,16.495,C,4461,375.0,185.0,mastercard,224.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
12,2987012,0,86564,50.000,W,3786,418.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2987013,0,86585,40.000,W,12866,303.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2987014,0,86596,10.500,W,11839,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2987015,0,86618,57.950,W,7055,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2987016,0,86620,30.000,H,1790,555.0,150.0,visa,226.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS
17,2987017,0,86668,100.000,H,11492,111.0,150.0,mastercard,219.0,...,chrome 62.0,24.0,1366x768,match_status:2,T,F,T,T,desktop,Windows
18,2987018,0,86725,47.950,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2987019,0,86730,186.000,W,7005,111.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
X = df_train.drop(columns=['isFraud'])
y = df_train['isFraud']
X.shape, y.shape

((590540, 433), (590540,))

# Train/test Split

In [12]:
from sklearn.model_selection import train_test_split



X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_val.shape

((472432, 433), (118108, 433))

In [13]:
import mlflow
import mlflow.xgboost
import matplotlib.pyplot as plt

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    roc_curve,
    precision_recall_curve,
    confusion_matrix,
    ConfusionMatrixDisplay
)


def run_experiment(
    model,
    run_name,
    experiment_name,
    X_train,
    X_val,
    y_train,
    y_val
):
    # Set experiment
    mlflow.set_experiment(experiment_name)

    with mlflow.start_run(run_name=run_name):

        # Train
        model.fit(X_train, y_train)

        # Predict
        probs = model.predict_proba(X_val)[:, 1]
        preds = model.predict(X_val)
        train_probs = model.predict_proba(X_train)[:, 1]
        train_auc = roc_auc_score(y_train, train_probs)
        # Metrics
        auc = roc_auc_score(y_val, probs)
        accuracy = accuracy_score(y_val, preds)
        recall = recall_score(y_val, preds)
        precision = precision_score(y_val, preds, zero_division=0)
        f1 = f1_score(y_val, preds, zero_division=0)

        fraud_mask = (y_val == 1)
        nonfraud_mask = (y_val == 0)
    
        mlflow.log_metrics({
            "train auc" : train_auc, 
            "auc": auc,
            "accuracy": accuracy,
            "recall": recall,
            "precision": precision,
            "f1": f1,
            "fraud_mean_prob": probs[fraud_mask].mean(),
            "nonfraud_mean_prob": probs[nonfraud_mask].mean()
        })

        # Log model parameters if available
        if hasattr(model, "get_params"):
            params = {k: str(v) for k, v in model.get_params().items()}
            mlflow.log_params(params)


        
        fpr, tpr, _ = roc_curve(y_val, probs)

        plt.figure()
        plt.plot(fpr, tpr, label=f"AUC = {auc:.4f}")
        plt.plot([0, 1], [0, 1], linestyle="--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("ROC Curve")
        plt.legend()

        mlflow.log_figure(plt.gcf(), "roc_curve.png")
        plt.close()

        precision_vals, recall_vals, _ = precision_recall_curve(y_val, probs)

        plt.figure()
        plt.plot(recall_vals, precision_vals)
        plt.xlabel("Recall")
        plt.ylabel("Precision")
        plt.title("Precision-Recall Curve")

        mlflow.log_figure(plt.gcf(), "pr_curve.png")
        plt.close()

      
        cm = confusion_matrix(y_val, preds)

        plt.figure()
        ConfusionMatrixDisplay(cm).plot()
        plt.title("Confusion Matrix")

        mlflow.log_figure(plt.gcf(), "confusion_matrix.png")
        plt.close()

       
        plt.figure()

        plt.hist(
            probs[nonfraud_mask],
            bins=50,
            alpha=0.5,
            label="non_fraud"
        )

        plt.hist(
            probs[fraud_mask],
            bins=50,
            alpha=0.5,
            label="fraud"
        )

        plt.xlabel("Predicted Probability")
        plt.ylabel("Count")
        plt.title("Prediction Score Distribution")
        plt.legend()

        mlflow.log_figure(
            plt.gcf(),
            "score_distribution.png"
        )
        plt.close()

        # Log model artifact
        mlflow.sklearn.log_model(model, "model")

        return {
            "auc": auc,
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1": f1
        }

# Preprocessing

In [14]:
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin


class MissingValueFilter(BaseEstimator, TransformerMixin):

    def __init__(
        self,
        column_threshold=0.9,
        row_threshold=None
    ):
        self.column_threshold = column_threshold
        self.row_threshold = row_threshold

    def fit(self, X, y=None):

        missing_ratio = X.isnull().mean()

        self.columns_to_keep_ = missing_ratio[
            missing_ratio <= self.column_threshold
        ].index.tolist()

        return self

    def transform(self, X):

        X = X.copy()

        X = X[self.columns_to_keep_]

        if self.row_threshold is not None:

            row_missing_ratio = X.isnull().mean(axis=1)

            X = X[
                row_missing_ratio <= self.row_threshold
            ]

        return X

In [15]:
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin


class NAPreprocessor(BaseEstimator, TransformerMixin):

    def __init__(
        self,
        numeric_strategy="median",
        categorical_strategy="mode"
    ):
        self.numeric_strategy = numeric_strategy
        self.categorical_strategy = categorical_strategy

    def fit(self, X, y=None):
        X = X.copy()

        self.fill_values_ = {}

        for col in X.columns:

            # Numeric columns
            if pd.api.types.is_numeric_dtype(X[col]):

                if self.numeric_strategy == "mean":
                    value = X[col].mean()

                elif self.numeric_strategy == "median":
                    value = X[col].median()

             

            # Categorical columns
            else:

                if self.categorical_strategy == "mode":

                    mode_vals = X[col].mode()

                    if len(mode_vals) > 0:
                        value = mode_vals.iloc[0]
                    else:
                        value = "missing"

                elif self.categorical_strategy == "constant":
                    value = "missing"


            self.fill_values_[col] = value

        return self

    def transform(self, X):
        X = X.copy()

        for col, fill_value in self.fill_values_.items():

            if col in X.columns:
                X[col] = X[col].fillna(fill_value)

        return X

In [16]:
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import OrdinalEncoder

class FraudPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.cat_cols = None
        self.num_cols = None
        self.encoder = None
        self.medians = None

    def fit(self, X, y=None):
        X = X.copy()
        self.cat_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
        self.num_cols = X.select_dtypes(include=[np.number, "bool"]).columns.tolist()
        self.medians = X[self.num_cols].median()
        if self.cat_cols:
            X[self.cat_cols] = X[self.cat_cols].fillna("missing")
            self.encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
            self.encoder.fit(X[self.cat_cols])
        return self

    def transform(self, X):
        X = X.copy()
        if self.cat_cols:
            X[self.cat_cols] = X[self.cat_cols].fillna("missing")
            if self.encoder is not None:
                X[self.cat_cols] = self.encoder.transform(X[self.cat_cols])
        for col in self.num_cols:
            if col in X.columns:
                X[col] = X[col].fillna(self.medians[col])
        for col in X.columns:
            X[col] = pd.to_numeric(X[col], errors="coerce")
        X = X.fillna(0)
        return X

In [17]:
import pandas as pd
import numpy as np

class WOEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, cols=None, smoothing=0.5):
        self.cols = cols
        self.smoothing = smoothing
        self.woe_maps = {}

    def fit(self, X, y):
        X = X.copy()
        cols = self.cols or X.select_dtypes(include=["object", "category"]).columns.tolist()
        
        total_events = y.sum()
        total_non_events = (1 - y).sum()

        for col in cols:
            tmp = pd.DataFrame({"col": X[col], "target": y.values})
            stats = tmp.groupby("col")["target"].agg(["sum", "count"])
            stats.columns = ["events", "count"]
            stats["non_events"] = stats["count"] - stats["events"]

            # smoothing to avoid log(0)
            stats["dist_events"]     = (stats["events"] + self.smoothing) / (total_events + self.smoothing)
            stats["dist_non_events"] = (stats["non_events"] + self.smoothing) / (total_non_events + self.smoothing)
            stats["woe"] = np.log(stats["dist_events"] / stats["dist_non_events"])

            self.woe_maps[col] = stats["woe"].to_dict()

        return self

    def transform(self, X):
        X = X.copy()
        for col, woe_map in self.woe_maps.items():
            if col in X.columns:
                X[col] = X[col].map(woe_map).fillna(0)  # unseen → 0 (neutral)
        return X

In [20]:
class CorrelationFilter(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        X = pd.DataFrame(X).copy()
        # Sample if too large
        if len(X) > 5000:
            X_sample = X.sample(5000, random_state=42)
        else:
            X_sample = X
            
        corr_matrix = X_sample.corr().abs()  # faster on sample
        upper = corr_matrix.where(
            np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
        )
        self.cols_to_drop_ = [col for col in upper.columns if any(upper[col] > 0.8)]
        print(self.cols_to_drop_)
        return self

    def transform(self, X):
        return pd.DataFrame(X).drop(columns=self.cols_to_drop_, errors='ignore')

In [19]:
woe_cols = X_train.select_dtypes(include=["object", "category"]).columns.tolist()
woe_cols

['ProductCD',
 'card4',
 'card6',
 'P_emaildomain',
 'R_emaildomain',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'id_12',
 'id_15',
 'id_16',
 'id_23',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

# Baseline

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
pipeline_lr = Pipeline([
    
    ("preprocess", FraudPreprocessor()),
    ("woe", WOEEncoder(cols=woe_cols)),
    ("scaler", StandardScaler()),
    ("correlation", CorrelationFilter()),
    ("model", LogisticRegression(
      
        class_weight="balanced",
        max_iter=10000,
        solver="saga",
        random_state=42
    ))
])

run_experiment(pipeline_lr, "Logistic Regression WOE", "Logistic Regression",
               X_train, X_val, y_train, y_val)

In [ ]:
run_experiment(pipeline, "Preprocessing Missing values 97%", "Preprocessing", X_train, X_val, y_train, y_val)

# Handling Imbalanced

Undersampling

In [ ]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline  # not sklearn

pipeline_lr = Pipeline([
    ("preprocess", FraudPreprocessor()),
    ("woe", WOEEncoder(cols=woe_cols)),
    ("corr_filter", CorrelationFilter()),
    ("scaler", StandardScaler()),
    ("undersample", RandomUnderSampler(random_state=42)),
    ("model", LogisticRegression(
        max_iter=1000,
        solver="saga",
        random_state=42
    ))
])

run_experiment(pipeline_lr, "LR Undersample", "Logistic Regression",
               X_train, X_val, y_train, y_val)

In [ ]:
run_experiment(pipeline, "Undersampling", "Handling Imbalanced", X_train, X_val, y_train, y_val)

# Feature Engineering

In [21]:
import pandas as pd
import numpy as np

def engineer_features(X, y=None):
    X = X.copy()

    X['amt_log'] = np.log1p(X['TransactionAmt'])
    X['amt_rounded'] = (X['TransactionAmt'] % 1 == 0).astype(int)  # whole number flag
    

    X['hour'] = (X['TransactionDT'] // 3600) % 24
    X['day_of_week'] = (X['TransactionDT'] // (3600 * 24)) % 7
    X['is_weekend'] = X['day_of_week'].isin([5, 6]).astype(int)

    X['email_match'] = (X['P_emaildomain'] == X['R_emaildomain']).astype(int)
    
    # --- Aggregates per card ---
    for col in ['card1', 'card2', 'card4', 'card6']:
        if col in X.columns:
            X[f'{col}_txn_count'] = X.groupby(col)['TransactionAmt'].transform('count')
            X[f'{col}_amt_mean']  = X.groupby(col)['TransactionAmt'].transform('mean')
            X[f'{col}_amt_std']   = X.groupby(col)['TransactionAmt'].transform('std')
            X[f'{col}_amt_dev']   = X['TransactionAmt'] - X[f'{col}_amt_mean']
            X[f'{col}_amt_zscore'] = X[f'{col}_amt_dev'] / (X[f'{col}_amt_std'] + 1e-9)

    for col in ['P_emaildomain', 'R_emaildomain']:
        if col in X.columns:
            X[f'{col}_freq'] = X.groupby(col)['TransactionAmt'].transform('count')

    if 'DeviceInfo' in X.columns:
        X['device_freq'] = X.groupby('DeviceInfo')['TransactionAmt'].transform('count')

    if y is not None:
        tmp = X.copy()
        tmp['target'] = y.values
        for col in ['card4', 'card6', 'P_emaildomain', 'DeviceType']:
            if col in X.columns:
                fraud_rate = tmp.groupby(col)['target'].transform('mean')
                X[f'{col}_fraud_rate'] = fraud_rate

    # --- Time since last transaction per card ---
    X = X.sort_values('TransactionDT')
    X['time_since_last_txn'] = X.groupby('card1')['TransactionDT'].diff().fillna(0)

    return X


# Usage
X_engineered = engineer_features(X, y)

In [22]:
from sklearn.model_selection import train_test_split



X_train_eng, X_val_eng, y_train, y_val = train_test_split(
    X_engineered, y,
    test_size=0.2,
    random_state=42
)

X_train_eng.shape, X_val_eng.shape

((472432, 467), (118108, 467))

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
woe_cols = X_train_eng.select_dtypes(include=["object", "category"]).columns.tolist()
print(woe_cols)
pipeline_lr = Pipeline([
   
    ("preprocess", FraudPreprocessor()),
    ("woe", WOEEncoder(cols=woe_cols)),
    ("scaler", StandardScaler()),
    ("correlation", CorrelationFilter()),
    ("model", LogisticRegression(
      
        class_weight="balanced",
        max_iter=1050,
        solver="saga",
        random_state=42
    ))
])

['ProductCD', 'card4', 'card6', 'P_emaildomain', 'R_emaildomain', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'id_12', 'id_15', 'id_16', 'id_23', 'id_27', 'id_28', 'id_29', 'id_30', 'id_31', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'DeviceInfo']

In [24]:
run_experiment(pipeline_lr, "Feature Engineering", "Logistic Regression", X_train_eng, X_val_eng, y_train, y_val)

[1, 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 46, 47, 50, 52, 53, 58, 62, 64, 66, 68, 69, 70, 71, 73, 74, 75, 79, 81, 83, 84, 85, 86, 87, 89, 91, 93, 95, 96, 97, 98, 100, 102, 103, 104, 105, 107, 110, 111, 112, 113, 115, 116, 117, 120, 122, 123, 124, 125, 126, 127, 129, 132, 133, 134, 136, 137, 138, 140, 143, 144, 145, 146, 147, 149, 150, 153, 154, 155, 156, 157, 158, 159, 163, 165, 166, 167, 169, 172, 178, 179, 180, 181, 185, 186, 187, 189, 190, 193, 194, 195, 196, 198, 200, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 230, 231, 232, 233, 234, 235, 236, 238, 239, 242, 243, 244, 245, 246, 248, 249, 250, 251, 252, 254, 255, 256, 257, 260, 262, 263, 264, 265, 266, 267, 268, 269, 271, 272, 275, 278, 283, 284, 285, 286, 287, 289, 290, 291, 292, 296, 297, 299, 300, 301, 302, 304, 305, 306, 307, 308, 309, 310, 311, 312, 316, 318, 319, 321, 322, 324, 325, 326, 327, 328, 331, 332, 333, 337, 338, 340, 342, 346, 347, 348, 349, 350, 351, 352, 354, 356, 357, 359, 360, 361, 362, 363, 365, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 379, 380, 381, 382, 383, 384, 385, 386, 388, 389, 390, 391, 392, 404, 407, 408, 409, 419, 420, 421, 423, 427, 428, 429, 430, 431, 437, 438, 442, 443, 446, 447, 448, 450, 452, 453, 454, 455, 456, 457, 458, 462, 463, 464]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2026/05/04 13:45:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/04 13:45:28 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run Feature Engineering at: https://dagshub.com/icosahedron31/IEEE-CIS-Fraud-Detection.mlflow/#/experiments/6/runs/0533c2d270f446dea2aa03a440e50bd7
🧪 View experiment at: https://dagshub.com/icosahedron31/IEEE-CIS-Fraud-Detection.mlflow/#/experiments/6

{'auc': np.float64(0.8495502745383576),
 'accuracy': 0.8183611609713144,
 'precision': 0.1309345113007677,
 'recall': 0.7197076850542197,
 'f1': 0.22156101455060054}

# Dropping some features

In [ ]:
print(X_train_eng.shape)
pipeline.fit(X_train_eng, y_train)

importances = pd.Series(
    pipeline['model'].feature_importances_,
    index=X_train_eng.columns 
)

threshold = importances.quantile(0.2)
drop_cols = importances[importances <= threshold].index.tolist()
print(f"Dropping {len(drop_cols)} columns: {drop_cols}")

X_train_reduced = X_train_eng.drop(columns=drop_cols)
X_val_reduced   = X_val_eng.drop(columns=drop_cols)

run_experiment(pipeline, "Drop Features 20% bigger model", "", X_train_reduced, X_val_reduced, y_train, y_val)